In [396]:
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
import pandas as pd
import re
from scipy.stats import ttest_ind
from statsmodels.stats.proportion import proportions_ztest
from scipy.stats import norm

In [361]:
pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.14.5-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.5 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from statsmodels) (2.2.4)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from statsmodels) (1.15.2)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from statsmodels) (2.2.3)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-1.0.1-py2.py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: packaging>=21.3 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from statsmodels) (24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Downloading statsmodels-0.14.5-cp313-cp313-macosx_11_0_arm64.whl (9.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 35.0 MB/s eta 0:00:00a 0:00:01
Downloading patsy-1.0.1-py2.py3-none-any.whl (232 kB)
Installing collected packages: patsy, statsmodels
Successfully installed patsy-1.0.1 statsmodels-0.14.5

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [369]:
df = pd.read_csv('Cars Datasets 2025.csv', encoding='latin-1')
df

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm
...,...,...,...,...,...,...,...,...,...,...,...
1213,Toyota,Crown Signia,2.5L Hybrid I4,2487 cc,240 hp,180 km/h,7.6 sec,"$43,590  $48,000",Hybrid (Gas + Electric),5,239 Nm
1214,Toyota,4Runner (6th Gen),2.4L Turbo I4 (i-FORCE MAX Hybrid),2393 cc + Battery,326 hp,180 km/h,6.8 sec,"$50,000",Hybrid,7,630 Nm
1215,Toyota,Corolla Cross,2.0L Gas / 2.0L Hybrid,1987 cc / Hybrid batt,169  196 hp,190 km/h,8.0  9.2 sec,"$25,210  $29,135",Gas / Hybrid,5,190  210 Nm
1216,Toyota,C-HR+,1.8L / 2.0L Hybrid,1798 / 1987 cc + batt,140  198 hp,180 km/h,7.9  10.5 sec," 33,000",Hybrid,5,190  205 Nm
1217,Toyota,RAV4 (6th Gen),2.5L Hybrid / Plug-in Hybrid,2487 cc + batt,219  302 hp,200 km/h,6.0  8.1 sec,"$29,000  $43,000",Hybrid / Plug-in,5,221  400 Nm

In [370]:
df_cleaned = df.copy()

# Set exchange rate
euro_to_usd = 1.1

def clean_price(price):
    if pd.isna(price):
        return None

    price_str = str(price).strip()

    # Remove "Math input error"
    price_str = price_str.replace("Math input error", "").strip()

    # Normalize dash characters
    price_str = price_str.replace("–", "-").replace("—", "-")

    # Handle Euro (e.g., €33,000)
    if "€" in price_str:
        match = re.search(r"€\s*([\d,]+)", price_str)
        if match:
            value = int(match.group(1).replace(",", ""))
            return round(value * euro_to_usd)

    # Handle price range (e.g., "12,000 - 15,000")
    range_match = re.match(r"([\d,]+)\s*-\s*([\d,]+)", price_str)
    if range_match:
        low = int(range_match.group(1).replace(",", ""))
        high = int(range_match.group(2).replace(",", ""))
        return (low + high) // 2

    # Handle standalone number (with optional $)
    num_match = re.search(r"([\d,]+)", price_str)
    if num_match:
        return int(num_match.group(1).replace(",", ""))

    return None

# Apply cleaner
df_cleaned["Cars Prices"] = df_cleaned["Cars Prices"].apply(clean_price)

# Rename the column
df_cleaned.rename(columns={"Cars Prices": "Cars Prices (USD)"}, inplace=True)

In [371]:
df_cleaned["Fuel Types"] = df_cleaned["Fuel Types"].str.replace("hyrbrid", "hybrid", case=False)

In [372]:
df_cleaned

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices (USD),Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"1,100,000",plug in hybrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"12,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"253,290",Petrol,2,560 Nm
...,...,...,...,...,...,...,...,...,...,...,...
1213,Toyota,Crown Signia,2.5L Hybrid I4,2487 cc,240 hp,180 km/h,7.6 sec,"43,590",Hybrid (Gas + Electric),5,239 Nm
1214,Toyota,4Runner (6th Gen),2.4L Turbo I4 (i-FORCE MAX Hybrid),2393 cc + Battery,326 hp,180 km/h,6.8 sec,"50,000",Hybrid,7,630 Nm
1215,Toyota,Corolla Cross,2.0L Gas / 2.0L Hybrid,1987 cc / Hybrid batt,169  196 hp,190 km/h,8.0  9.2 sec,"25,210",Gas / Hybrid,5,190  210 Nm
1216,Toyota,C-HR+,1.8L / 2.0L Hybrid,1798 / 1987 cc + batt,140  198 hp,180 km/h,7.9  10.5 sec,"33,000",Hybrid,5,190  205 Nm
1217,Toyota,RAV4 (6th Gen),2.5L Hybrid / Plug-in Hybrid,2487 cc + batt,219  302 hp,200 km/h,6.0  8.1 sec,"29,000",Hybrid / Plug-in,5,221  400 Nm

In [373]:
hybrid_cars = df_cleaned[df_cleaned["Fuel Types"].str.contains("hybrid", case=False, na=False)]
hybrid_cars["Fuel Types"] = "Hybrid"
hybrid_cars[["Cars Names", "Cars Prices (USD)", "Fuel Types"]]

/var/folders/8z/9f9b14l53y99c8m3pl4l8krc0000gn/T/ipykernel_36098/2669565428.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hybrid_cars["Fuel Types"] = "Hybrid"

             Cars Names  Cars Prices (USD) Fuel Types
0         SF90 STRADALE          1,100,000     Hybrid
32             VALKYRIE          3,200,000     Hybrid
33             VALHALLA          1,100,000     Hybrid
42                 SIAN          2,800,000     Hybrid
142         I8 ROADSTER            165,000     Hybrid
...                 ...                ...        ...
1213       Crown Signia             43,590     Hybrid
1214  4Runner (6th Gen)             50,000     Hybrid
1215      Corolla Cross             25,210     Hybrid
1216             C-HR+              33,000     Hybrid
1217     RAV4 (6th Gen)             29,000     Hybrid

[114 rows x 3 columns]

In [314]:
hybrid_cars.describe()

       Cars Prices (USD)
count                113
mean             131,217
std              416,725
min               15,400
25%               31,100
50%               43,400
75%               55,000
max            3,200,000

In [374]:
hybrid_cars = df_cleaned[df_cleaned["Fuel Types"].str.contains("hybrid", case=False, na=False)]

hybrid_cars[["Cars Names", "Cars Prices (USD)", "Fuel Types"]]

             Cars Names  Cars Prices (USD)               Fuel Types
0         SF90 STRADALE          1,100,000           plug in hybrid
32             VALKYRIE          3,200,000                   Hybrid
33             VALHALLA          1,100,000                   Hybrid
42                 SIAN          2,800,000                   Hybrid
142         I8 ROADSTER            165,000                   Hybrid
...                 ...                ...                      ...
1213       Crown Signia             43,590  Hybrid (Gas + Electric)
1214  4Runner (6th Gen)             50,000                   Hybrid
1215      Corolla Cross             25,210             Gas / Hybrid
1216             C-HR+              33,000                   Hybrid
1217     RAV4 (6th Gen)             29,000         Hybrid / Plug-in

[114 rows x 3 columns]

In [375]:
df_cleaned["Fuel Types"].unique()

array(['plug in hybrid', 'Petrol', 'Diesel', 'Hybrid', 'Electric',
       'Petrol/Diesel', 'Plug-in Hybrid', 'Petrol/AWD', 'Petrol/Hybrid',
       'Hydrogen', 'Diesel/Petrol', 'Petrol/EV', 'Hybrid/Electric',
       'Petrol, Hybrid', 'Petrol, Diesel', 'Hybrid (Petrol)',
       'CNG/Petrol', 'Hybrid/Petrol', 'Diesel Hybrid', 'Petrol (Hybrid)',
       'Hybrid (Gas + Electric)', 'Gas / Hybrid', 'Hybrid / Plug-in'],
      dtype=object)

In [376]:
# Normalize Fuel Types column
fuel_col = df_cleaned["Fuel Types"].str.lower().fillna("")

# Include anything that contains "petrol" or "gas"
is_petrol_or_gas = fuel_col.str.contains("petrol") | fuel_col.str.contains("gas")

# Exclude if it also contains "hybrid", "electric", or "plug"
not_mixed = ~fuel_col.str.contains("hybrid|electric|plug")

# Final filter for pure gas cars
pure_gas_mask = is_petrol_or_gas & not_mixed

# Create a new DataFrame of just gas cars
gas_cars = df_cleaned[pure_gas_mask].copy()

# Optional: Rename their fuel type to "Gas"
gas_cars["Fuel Types"] = "Gas"

In [311]:
gas_cars[["Cars Names", "Cars Prices (USD)", "Fuel Types"]]

             Cars Names  Cars Prices (USD) Fuel Types
1               PHANTOM            460,000        Gas
2                   KA+             12,000        Gas
3               GT 63 S            161,000        Gas
4            AUDI R8 Gt            253,290        Gas
5          Mclaren 720s            499,000        Gas
...                 ...                ...        ...
1208        Bongo Truck             15,000        Gas
1209      Rotary Pickup             18,000        Gas
1210  Luce Rotary Coupe             25,000        Gas
1211         Millenia S             30,000        Gas
1212    787B (Race Car)          5,000,000        Gas

[898 rows x 3 columns]

In [310]:
gas_cars.describe()

       Cars Prices (USD)  Torque (Nm)  Performance (0 - 60 MPH)
count                898          898                       898
mean             156,398          412                         7
std              806,000          242                         3
min                4,000           45                         2
25%               25,418          237                         5
50%               41,640          366                         7
75%               72,150          550                         9
max           18,000,000        1,600                        34

In [377]:
group1 = gas_cars[gas_cars['Fuel Types'] == 'Gas']['Cars Prices (USD)'].dropna()
group2 = hybrid_cars[hybrid_cars['Fuel Types'] == 'Hybrid']['Cars Prices (USD)'].dropna()

t_stat, p_val = ttest_ind(group1, group2, equal_var=False)

print("t-statistic:", t_stat)
print("p-value:", p_val)

t-statistic: 0.031638207451621096
p-value: 0.9748129913411534

# Since p-value is greater than alpha we fail to reject the null hypothesis at 0.05 significance level. There is no statistically significant difference in the average prices of gas cars and hybrid cars in your dataset. The observed difference in means could just be due to random chance.

In [378]:
def clean_torque(val):
    if pd.isna(val):
        return None
    
    # Ensure string, strip whitespace, remove 'Nm' and extra spaces
    val = str(val).replace("Nm", "").strip()
    
    # Normalize dashes and spaces (e.g., '100 - 140', '100–140', '190 210')
    val = re.sub(r"[–\-]", "-", val)  # replace dash variants with hyphen
    numbers = re.findall(r"\d+", val)
    
    # Convert to numbers
    numbers = [int(n) for n in numbers]
    
    if len(numbers) == 1:
        return numbers[0]
    elif len(numbers) >= 2:
        return sum(numbers[:2]) / 2  # average of first two numbers
    else:
        return None

# Apply to your dataframe
hybrid_cars["Torque (Nm)"] = hybrid_cars["Torque"].apply(clean_torque)

# Drop or keep the original column
hybrid_cars = hybrid_cars.drop(columns=["Torque"])

/var/folders/8z/9f9b14l53y99c8m3pl4l8krc0000gn/T/ipykernel_36098/3882784483.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hybrid_cars["Torque (Nm)"] = hybrid_cars["Torque"].apply(clean_torque)

In [379]:
def clean_torque(val):
    if pd.isna(val):
        return None
    
    val = str(val).replace("Nm", "").strip()
    val = re.sub(r"[–\-]", "-", val)  # normalize dashes
    numbers = re.findall(r"\d+", val)
    numbers = [int(n) for n in numbers]

    if len(numbers) == 1:
        return numbers[0]
    elif len(numbers) >= 2:
        return sum(numbers[:2]) / 2  # average of first two
    else:
        return None

# Apply it to gas_cars
gas_cars["Torque (Nm)"] = gas_cars["Torque"].apply(clean_torque)

# Drop original column if no longer needed
gas_cars = gas_cars.drop(columns=["Torque"])

In [380]:
gas_cars[["Cars Names", "Torque (Nm)"]]

             Cars Names  Torque (Nm)
1               PHANTOM          900
2                   KA+          120
3               GT 63 S          900
4            AUDI R8 Gt          560
5          Mclaren 720s          770
...                 ...          ...
1208        Bongo Truck          150
1209      Rotary Pickup          160
1210  Luce Rotary Coupe          180
1211         Millenia S          250
1212    787B (Race Car)          500

[898 rows x 2 columns]

In [381]:
gas_cars.describe()

       Cars Prices (USD)  Torque (Nm)
count                898          898
mean             156,398          412
std              806,000          242
min                4,000           45
25%               25,418          237
50%               41,640          366
75%               72,150          550
max           18,000,000        1,600

In [382]:
hybrid_cars[["Cars Names", "Torque (Nm)"]]

             Cars Names  Torque (Nm)
0         SF90 STRADALE          800
32             VALKYRIE          900
33             VALHALLA        1,000
42                 SIAN          720
142         I8 ROADSTER          570
...                 ...          ...
1213       Crown Signia          239
1214  4Runner (6th Gen)          630
1215      Corolla Cross          200
1216             C-HR+           198
1217     RAV4 (6th Gen)          310

[114 rows x 2 columns]

In [383]:
hybrid_cars.describe()

       Cars Prices (USD)  Torque (Nm)
count                113          113
mean             131,217          424
std              416,725          209
min               15,400          140
25%               31,100          265
50%               43,400          352
75%               55,000          570
max            3,200,000        1,000

In [384]:
group1 = gas_cars[gas_cars['Fuel Types'] == 'Gas']['Torque (Nm)'].dropna()
group2 = hybrid_cars[hybrid_cars['Fuel Types'] == 'Hybrid']['Torque (Nm)'].dropna()

t_stat, p_val = ttest_ind(group1, group2, equal_var=False)

print("t-statistic:", t_stat)
print("p-value:", p_val)

t-statistic: -1.2779179449865876
p-value: 0.20432647906206217

# Since p-value is greater than alpha we fail to reject the null hypothesis at 0.05 significance level. There is no statistically significant difference in the mean torque between gas and hybrid cars. The data do not provide evidence to suggest that the average torque differs between the two fuel types.

In [385]:
hybrid_cars

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices (USD),Fuel Types,Seats,Torque (Nm)
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"1,100,000",plug in hybrid,2,800
32,ASTON MARTIN,VALKYRIE,V12,"6,496 cc",1160 hp,402 km/h,2.5 sec,"3,200,000",Hybrid,2,900
33,ASTON MARTIN,VALHALLA,V8,"3,996 cc",1000 hp,362 km/h,2.5 sec,"1,100,000",Hybrid,2,"1,000"
42,LAMBORGHINI,SIAN,V12,"6,498 cc",819 hp,350 km/h,2.8 sec,"2,800,000",Hybrid,2,720
142,BMW,I8 ROADSTER,ELECTRIC MOTOR,11.6 kwh,369 hp,250 km/h,4.4 sec,"165,000",Hybrid,2,570
...,...,...,...,...,...,...,...,...,...,...,...
1213,Toyota,Crown Signia,2.5L Hybrid I4,2487 cc,240 hp,180 km/h,7.6 sec,"43,590",Hybrid (Gas + Electric),5,239
1214,Toyota,4Runner (6th Gen),2.4L Turbo I4 (i-FORCE MAX Hybrid),2393 cc + Battery,326 hp,180 km/h,6.8 sec,"50,000",Hybrid,7,630
1215,Toyota,Corolla Cross,2.0L Gas / 2.0L Hybrid,1987 cc / Hybrid batt,169  196 hp,190 km/h,8.0  9.2 sec,"25,210",Gas / Hybrid,5,200
1216,Toyota,C-HR+,1.8L / 2.0L Hybrid,1798 / 1987 cc + batt,140  198 hp,180 km/h,7.9  10.5 sec,"33,000",Hybrid,5,198
1217,Toyota,RAV4 (6th Gen),2.5L Hybrid / Plug-in Hybrid,2487 cc + batt,219  302 hp,200 km/h,6.0  8.1 sec,"29,000",Hybrid / Plug-in,5,310

In [386]:
print(hybrid_cars.columns.tolist())

['Company Names', 'Cars Names', 'Engines', 'CC/Battery Capacity', 'HorsePower', 'Total Speed', 'Performance(0 - 100 )KM/H', 'Cars Prices (USD)', 'Fuel Types', 'Seats', 'Torque (Nm)']

In [387]:
hybrid_cars = hybrid_cars.rename(columns={"Performance(0 - 100 )KM/H": "Performance_kmh"})

In [388]:
def clean_and_convert(performance_str):
    if pd.isna(performance_str):
        return None

    # Normalize weird dashes
    normalized = str(performance_str)
    normalized = re.sub(r'[–—‑−]', '-', normalized)
    normalized = normalized.replace('to', '-')

    # Extract numbers
    numbers = re.findall(r'\d+\.?\d*', normalized)

    if len(numbers) == 2:
        avg_kmh = (float(numbers[0]) + float(numbers[1])) / 2
    elif len(numbers) == 1:
        avg_kmh = float(numbers[0])
    else:
        return None

    # Convert to 0–60 MPH
    return avg_kmh / 1.036

In [389]:
hybrid_cars["Performance (0 - 60 MPH)"] = hybrid_cars["Performance_kmh"].apply(clean_and_convert)

In [390]:
hybrid_cars

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance_kmh,Cars Prices (USD),Fuel Types,Seats,Torque (Nm),Performance (0 - 60 MPH)
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"1,100,000",plug in hybrid,2,800,2
32,ASTON MARTIN,VALKYRIE,V12,"6,496 cc",1160 hp,402 km/h,2.5 sec,"3,200,000",Hybrid,2,900,2
33,ASTON MARTIN,VALHALLA,V8,"3,996 cc",1000 hp,362 km/h,2.5 sec,"1,100,000",Hybrid,2,"1,000",2
42,LAMBORGHINI,SIAN,V12,"6,498 cc",819 hp,350 km/h,2.8 sec,"2,800,000",Hybrid,2,720,3
142,BMW,I8 ROADSTER,ELECTRIC MOTOR,11.6 kwh,369 hp,250 km/h,4.4 sec,"165,000",Hybrid,2,570,4
...,...,...,...,...,...,...,...,...,...,...,...,...
1213,Toyota,Crown Signia,2.5L Hybrid I4,2487 cc,240 hp,180 km/h,7.6 sec,"43,590",Hybrid (Gas + Electric),5,239,7
1214,Toyota,4Runner (6th Gen),2.4L Turbo I4 (i-FORCE MAX Hybrid),2393 cc + Battery,326 hp,180 km/h,6.8 sec,"50,000",Hybrid,7,630,7
1215,Toyota,Corolla Cross,2.0L Gas / 2.0L Hybrid,1987 cc / Hybrid batt,169  196 hp,190 km/h,8.0  9.2 sec,"25,210",Gas / Hybrid,5,200,8
1216,Toyota,C-HR+,1.8L / 2.0L Hybrid,1798 / 1987 cc + batt,140  198 hp,180 km/h,7.9  10.5 sec,"33,000",Hybrid,5,198,9
1217,Toyota,RAV4 (6th Gen),2.5L Hybrid / Plug-in Hybrid,2487 cc + batt,219  302 hp,200 km/h,6.0  8.1 sec,"29,000",Hybrid / Plug-in,5,310,7

In [391]:
styled_hybrid_df = hybrid_cars[["Company Names", "Fuel Types", "Cars Names", "Performance (0 - 60 MPH)"]] # Add all columns you want to see
styled_selected_columns = styled_hybrid_df.style.format({"Performance (0 - 60 MPH)": '{:.4f}'})

In [392]:
styled_selected_columns

In [393]:
condition_fast_hybrid_cars = styled_hybrid_df["Performance (0 - 60 MPH)"] < 5
fast_hybrid_cars_df = hybrid_cars[condition_fast_hybrid_cars].copy()

In [394]:
fast_hybrid_cars_df

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance_kmh,Cars Prices (USD),Fuel Types,Seats,Torque (Nm),Performance (0 - 60 MPH)
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"1,100,000",plug in hybrid,2,800,2
32,ASTON MARTIN,VALKYRIE,V12,"6,496 cc",1160 hp,402 km/h,2.5 sec,"3,200,000",Hybrid,2,900,2
33,ASTON MARTIN,VALHALLA,V8,"3,996 cc",1000 hp,362 km/h,2.5 sec,"1,100,000",Hybrid,2,"1,000",2
42,LAMBORGHINI,SIAN,V12,"6,498 cc",819 hp,350 km/h,2.8 sec,"2,800,000",Hybrid,2,720,3
142,BMW,I8 ROADSTER,ELECTRIC MOTOR,11.6 kwh,369 hp,250 km/h,4.4 sec,"165,000",Hybrid,2,570,4
299,Volkswagen,Touareg R,Plug-in Hybrid V6,2995 cc,462 hp,250 km/h,5.1 sec,"70,000",Hybrid,5,700,5
466,Nissan,GT-R LM NISMO,3.0L Twin-Turbo V6 Hybrid,3000 cc,500 HP,320 km/h,3.0 sec,"600,000",Hybrid,2,650,3
534,Porsche,Panamera E-Hybrid,2.9L V6 + Electric Motor,17.9 kWh Battery,455 HP,280 km/h,4.4 sec,"115,000",Hybrid (Petrol),4,700,4
535,Porsche,Panamera 4 E-Hybrid Sport Turismo,2.9L V6 + Electric Motor,17.9 kWh Battery,455 HP,280 km/h,4.4 sec,"120,000",Hybrid (Petrol),4,700,4
536,Porsche,Panamera Turbo S E-Hybrid,4.0L V8 + Electric Motor,17.9 kWh Battery,690 HP,315 km/h,3.2 sec,"190,000",Hybrid (Petrol),4,870,3
543,Porsche,Cayenne Turbo S E-Hybrid,4.0L V8 + Electric Motor,17.9 kWh Battery,670 HP,295 km/h,3.6 sec,"170,000",Hybrid (Petrol),5,900,3
574,Porsche,Panamera 4 E-Hybrid,2.9L Twin-Turbo V6 + Electric Motor,2894 cc,462 hp,280 km/h,4.4,"113,300",Hybrid,4,700,4
576,Porsche,Panamera Turbo S E-Hybrid Sport Turismo,4.0L Twin-Turbo V8 + Electric Motor,3996 cc,690 hp,315 km/h,3.2,"200,200",Hybrid,4,870,3
577,Porsche,Panamera 4S E-Hybrid Executive,2.9L Twin-Turbo V6 + Electric Motor,2894 cc,560 hp,295 km/h,3.7,"128,900",Hybrid,4,750,4
589,Porsche,Cayenne E-Hybrid,3.0L V6 + Electric Motor,2995 cc,455 hp,253 km/h,4.8,"91,000",Hybrid,5,700,5
593,Porsche,Cayenne Turbo S E-Hybrid Coupe,4.0L Twin-Turbo V8 + Electric Motor,3996 cc,670 hp,295 km/h,3.6,"167,800",Hybrid,4,900,3
597,Porsche,Cayenne Coupe Turbo E-Hybrid,4.0L Twin-Turbo V8 + Electric Motor,3996 cc,728 hp,295 km/h,3.6,"182,900",Hybrid,4,950,3
937,Jaguar Land Rover,Jaguar F-PACE P400e Plug-in Hybrid,I4 Petrol + Electric Motor,1999 cc (I4) + Electric,398 hp,220 km/h,5.1 sec,"75,000",Plug-in Hybrid,5,640,5
939,Acura,NSX Type S,Twin-Turbo V6 Hybrid,"3,493 cc (V6)",600 hp,307 km/h,2.9 sec,"157,000",Hybrid,2,666,3
953,Acura,NSX GT3 (Track Version),Twin-Turbo V6 Hybrid,"3,493 cc",500 hp,300 km/h,3.0 sec,"150,000",Hybrid,2,600,3
958,Acura,NSX 3.5L Hybrid Coupe,Twin-Turbo V6 Hybrid,"3,493 cc",537 hp,307 km/h,2.9 sec,"157,000",Hybrid,2,666,3
961,Acura,NSX Carbon Edition,Twin-Turbo V6 Hybrid,"3,493 cc",537 hp,307 km/h,2.9 sec,"157,000",Hybrid,2,666,3
997,Peugeot,308 PSE,Hybrid I4,"1,598 cc (petrol) + Electric Motor",360 hp,250 km/h,5.0 sec,"55,000",Hybrid,5,520,5

In [395]:
fast_hybrid_cars_df.count()

Company Names               23
Cars Names                  23
Engines                     23
CC/Battery Capacity         23
HorsePower                  23
Total Speed                 23
Performance_kmh             23
Cars Prices (USD)           23
Fuel Types                  23
Seats                       23
Torque (Nm)                 23
Performance (0 - 60 MPH)    23
dtype: int64

# ----------------

In [295]:
gas_cars

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices (USD),Fuel Types,Seats,Torque (Nm)
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"460,000",Gas,5,900
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"12,000",Gas,5,120
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"161,000",Gas,4,900
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"253,290",Gas,2,560
5,BMW,Mclaren 720s,V8,"3,994 cc",710 hp,341 km/h,2.9 sec,"499,000",Gas,2,770
...,...,...,...,...,...,...,...,...,...,...,...
1208,Mazda,Bongo Truck,2.0L Inline-4,"1,998 cc",120 hp,130 km/h,15.0 sec,"15,000",Gas,2,150
1209,Mazda,Rotary Pickup,1.3L Wankel Rotary Engine,"1,308 cc",130 hp,150 km/h,14.5 sec,"18,000",Gas,2,160
1210,Mazda,Luce Rotary Coupe,1.3L Wankel Rotary Engine,"1,308 cc",135 hp,175 km/h,12.0 sec,"25,000",Gas,4,180
1211,Mazda,Millenia S,2.5L V6,"2,500 cc",200 hp,220 km/h,8.0 sec,"30,000",Gas,5,250
1212,Mazda,787B (Race Car),2.6L Wankel Rotary Engine,"2,620 cc",700 hp,320 km/h,3.5 sec,"5,000,000",Gas,1,500

In [321]:
print(gas_cars.columns.tolist())

['Company Names', 'Cars Names', 'Engines', 'CC/Battery Capacity', 'HorsePower', 'Total Speed', 'Performance_kmh', 'Cars Prices (USD)', 'Fuel Types', 'Seats', 'Torque (Nm)', 'Performance (0 - 60 MPH)']

In [299]:
gas_cars = gas_cars.rename(columns={"Performance(0 - 100 )KM/H": "Performance_kmh"})

In [300]:
gas_cars["Performance (0 - 60 MPH)"] = gas_cars["Performance_kmh"].apply(clean_and_convert)

In [324]:
gas_cars

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance_kmh,Cars Prices (USD),Fuel Types,Seats,Torque (Nm),Performance (0 - 60 MPH)
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"460,000",Gas,5,900,5
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"12,000",Gas,5,120,10
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"161,000",Gas,4,900,3
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"253,290",Gas,2,560,3
5,BMW,Mclaren 720s,V8,"3,994 cc",710 hp,341 km/h,2.9 sec,"499,000",Gas,2,770,3
...,...,...,...,...,...,...,...,...,...,...,...,...
1208,Mazda,Bongo Truck,2.0L Inline-4,"1,998 cc",120 hp,130 km/h,15.0 sec,"15,000",Gas,2,150,14
1209,Mazda,Rotary Pickup,1.3L Wankel Rotary Engine,"1,308 cc",130 hp,150 km/h,14.5 sec,"18,000",Gas,2,160,14
1210,Mazda,Luce Rotary Coupe,1.3L Wankel Rotary Engine,"1,308 cc",135 hp,175 km/h,12.0 sec,"25,000",Gas,4,180,12
1211,Mazda,Millenia S,2.5L V6,"2,500 cc",200 hp,220 km/h,8.0 sec,"30,000",Gas,5,250,8
1212,Mazda,787B (Race Car),2.6L Wankel Rotary Engine,"2,620 cc",700 hp,320 km/h,3.5 sec,"5,000,000",Gas,1,500,3

In [317]:
styled_gas_df = gas_cars[["Company Names", "Fuel Types", "Cars Names", "Performance (0 - 60 MPH)"]] # Add all columns you want to see
styled_selected_columns_gas = styled_gas_df.style.format({"Performance (0 - 60 MPH)": '{:.4f}'})

In [318]:
styled_selected_columns_gas

In [349]:
condition_fast_gas_cars = styled_gas_df["Performance (0 - 60 MPH)"] < 5
fast_gas_cars_df = gas_cars[condition_fast_gas_cars].copy()

In [350]:
fast_gas_cars_df

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance_kmh,Cars Prices (USD),Fuel Types,Seats,Torque (Nm),Performance (0 - 60 MPH)
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"161,000",Gas,4,900,3
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"253,290",Gas,2,560,3
5,BMW,Mclaren 720s,V8,"3,994 cc",710 hp,341 km/h,2.9 sec,"499,000",Gas,2,770,3
6,ASTON MARTIN,VANTAGE F1,V8,"3,982 cc",656 hp,314 km/h,3.6 sec,"193,440",Gas,2,685,3
7,BENTLEY,Continental GT Azure,V8,"3,996 cc",550 hp,318 km/h,4.0 sec,"311,000",Gas,4,900,4
...,...,...,...,...,...,...,...,...,...,...,...,...
1050,Ford,Mustang Shelby GT500,Supercharged V8,"5,200 cc",760 hp,290 km/h,3.5 sec,"79,420",Gas,2,847,3
1051,Ford,Mustang Shelby GT350,Naturally Aspirated V8,"5,200 cc",526 hp,280 km/h,4.0 sec,"59,140",Gas,2,582,4
1062,Ford,Mustang (2024),V8 Gasoline Engine,"5,000 cc",450 hp,250 km/h,4.5 sec,"60,000",Gas,4,570,4
1076,Mitsubishi,Lancer Evolution X,2.0L Turbocharged,"2,000 cc",291 hp,240 km/h,5.0 sec,"40,000",Gas,5,407,5
1212,Mazda,787B (Race Car),2.6L Wankel Rotary Engine,"2,620 cc",700 hp,320 km/h,3.5 sec,"5,000,000",Gas,1,500,3

In [358]:
fast_gas_cars_df.count()

Company Names               220
Cars Names                  220
Engines                     220
CC/Battery Capacity         220
HorsePower                  220
Total Speed                 220
Performance_kmh             220
Cars Prices (USD)           220
Fuel Types                  220
Seats                       220
Torque (Nm)                 220
Performance (0 - 60 MPH)    220
dtype: int64

In [398]:
# Successes and sample sizes
x1, n1 = 220, 898  # Gas_Cars
x2, n2 = 23, 114  # Hybrid_Cars

# Sample proportions
p1 = x1 / n1
p2 = x2 / n2

# Pooled proportion (under H0)
p_pool = (x1 + x2) / (n1 + n2)

# Standard error
se = np.sqrt(p_pool * (1 - p_pool) * (1/n1 + 1/n2))

# Z-score
z = (p1 - p2) / se

# Two-tailed p-value
p_value = 2 * (1 - norm.cdf(abs(z)))

print(f"Z-statistic: {z:.4f}")
print(f"P-value: {p_value:.4f}")

Z-statistic: 1.0180
P-value: 0.3087

# Since p-value = 0.3087 is greater than any common alpha level (like 0.05 or 0.01), you fail to reject the null hypothesis. Conclusion: You do not have statistically significant evidence to say that the proportion of high-performance gas cars is different from that of hybrid cars.